(
    WAITING_PRODUCT_PHOTO,
    WAITING_DESCRIPTION,
    ASKING_ADD_PHOTO,
    WAITING_ADDITIONAL_PHOTO,
    WAITING_PHOTO_DESC,
    CHOOSING_MODEL_TYPE,
    WAITING_GENDER,
    WAITING_AGE_GROUP,
    WAITING_AI_CONFIRM,
    WAITING_MODEL_UPLOAD,
) = range(10)
